server:
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

spring:
  aop:
    proxy-target-class: true
    auto: true


datasource:
driver-class-name: com.mysql.jdbc.Driver
filters: stat,wall
druid:
  initial-size: 50
  min-idle: 50
  max-active: 100
  test-on-borrow: true
  time-between-eviction-runs-millis: 60000
  min-evictable-idle-time-millis: 300000
  web-stat-filter:
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000

paascloud:
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120