

spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://47.99.247.149:3306/study?autoReconnect=true&useUnicode=true&characterEncoding=utf-8


#mybaits
mybatis:
  mapper-locations:
   classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
logging:
  level: 
    org.service.admin.mapper:debug